apiVersion: v1
clusters:
- cluster:
    server: ""
  name: ctx1-test
contexts:
- context:
    cluster: ""
    user: ""
  name: ctx1-test
current-context: ctx1-test
kind: Config
preferences: {}
users:
- name: ctx1-test
  user: {}
